#!/bin/bash
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-10 --online_params.threshold 10
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-15 --online_params.threshold 15
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-20 --online_params.threshold 20
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-25 --online_params.threshold 25
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-30 --online_params.threshold 30
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-35 --online_params.threshold 35
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-40 --online_params.threshold 40
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-45 --online_params.threshold 45
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-50 --online_params.threshold 50
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-55 --online_params.threshold 55
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-60 --online_params.threshold 60
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-65 --online_params.threshold 65
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-70 --online_params.threshold 70
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-75 --online_params.threshold 75
python online_attacks/experiments/toy.py --online_params.online_type stochastic_optimistic --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Optimistic-80 --online_params.threshold 80

# Virtual
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-10 --online_params.threshold 10
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-15 --online_params.threshold 15
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-20 --online_params.threshold 20
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-25 --online_params.threshold 25
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-30 --online_params.threshold 30
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-35 --online_params.threshold 35
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-40 --online_params.threshold 40
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-45 --online_params.threshold 45
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-50 --online_params.threshold 50
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-55 --online_params.threshold 55
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-60 --online_params.threshold 60
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-65 --online_params.threshold 65
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-70 --online_params.threshold 70
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-75 --online_params.threshold 75
python online_attacks/experiments/toy.py --online_params.online_type stochastic_virtual --wandb --online_params.N 100 --max_perms 10000 --K 20 --eps 5.0  --namestr Var5-NoPick-Toy-Stochastic-Virtual-80 --online_params.threshold 80
